### ISSUE TITLE
missing linebreak in tweetview

### ISSUE THREAD

**Issue by fager** [pilhuhn/ZwitscherA#82]
No linewrap in tweetviews on smal displays (Defy). Only first xx chars of a message displayed.

**Comment by fager** [comment]
A screenshot...

https://picasaweb.google.com/lh/photo/Icc_7MJCw17zZ0ZgjLSJQNMTjNZETYmyPJy0liipFm0

**Comment by pilhuhn** [comment]
Thanks for your feedback. I got a report from someone else like this, but am not able to reproduce. The size of the screenshot is 480×854, so not even a unusually small display (like 320x200).
What software version are you running?

**Comment by pilhuhn** [comment]
I have pushed v087 to the market - could you check if the change in it solves the issue?

**Comment by fager** [comment]
problem is still reproducible.
Zwittscher 0.87
Android 2.3.7 (CyanogenMod 7.2.0-RC2)

Checked my device log. No Exception and error messages from zwitscher.

Is there a way to get Debug-Outputs from the application?

**Comment by pilhuhn** [comment]
It looks like this is an issue with how the TextView does things. TextView should by itself wrap the lines and does so on my SGN with 4.0.4, HTC Desire with 2.2 and Xoom with 3.2 -- all with stock software, not rooted.

Zwitscher does not try to "manually" wrap here, so I suspect debug logging will not help a lot.

**Comment by fager** [comment]
I Found some Infos on this behavior. But Android is not in my list of Programming Platforms... ;-)
Maybe it helps...
http://stackoverflow.com/questions/2197744/android-textview-text-not-getting-wrapped

**Comment by pilhuhn** [comment]
You see, there are so many of tips like that out there :-) And I have tried a lot of them :-) But not this one.
Can I send you the apk via email so you can install locally and re-try?

**Comment by fager** [comment]
EMail postet in private G+ Message...
